src/Entity/Recursos.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RecursosRepository")
 */
class Recursos
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $Nombre;


    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $Fecha_devolucion;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorias", inversedBy="categorias")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Categoria;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="email_id")
     * @ORM\JoinColumn(nullable=true)
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\User", mappedBy="recurso")
     */
    private $recurso;

    public function __construct()
    {
        $this->recurso = new ArrayCollection();
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getFechaDevolucion(): ?\DateTimeInterface
    {
        return $this->Fecha_devolucion;
    }

    public function setFechaDevolucion(?\DateTimeInterface $Fecha_devolucion): self
    {
        $this->Fecha_devolucion = $Fecha_devolucion;

        return $this;
    }

    public function getCategoria(): ?Categorias
    {
        return $this->Categoria;
    }

    public function setCategoria(?Categorias $Categoria): self
    {
        $this->Categoria = $Categoria;

        return $this;
    }

    public function getEmail(): ?User
    {
        return $this->email;
    }

    public function setEmail(?User $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getRecurso(): Collection
    {
        return $this->recurso;
    }

    public function addRecurso(User $recurso): self
    {
        if (!$this->recurso->contains($recurso)) {
            $this->recurso[] = $recurso;
            $recurso->setRecurso($this);
        }

        return $this;
    }

    public function removeRecurso(User $recurso): self
    {
        if ($this->recurso->contains($recurso)) {
            $this->recurso->removeElement($recurso);
            // set the owning side to null (unless already changed)
            if ($recurso->getRecurso() === $this) {
                $recurso->setRecurso(null);
            }
        }

        return $this;
    }

}

src/Controller/RecursosController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EntityType;
use App\Repository\RecursosRepository;
use App\Form\RecursosType;
use App\Entity\Recursos;
use App\Entity\User;
use App\Entity\Categorias;
use App\Repository\UserRepository;
use App\Repository\CategoriasRepository;
use Doctrine\ORM\EntityManager;


class RecursosController extends AbstractController
{
    /**
     * @Route("/recursos", name="recursos_lista")
     */
    public function lista(Request $request)    {

        $recursos = $this->getDoctrine()->getRepository(Recursos::class)->findAll();

        return $this->render('recursos/index.html.twig', [
            'recursos' => $recursos,
        ]);
    }
    /**
     * @Route("/recursos/agregar", name="recursos_agregar")
     */
    public function agregar(Request $request)    {
        $recursos = new Recursos;
        $user = $this->getDoctrine()->getRepository(User::class)->findAll();
        $categorias = $this->getDoctrine()->getRepository(categorias::class)->findAll();
        $form = $this->createFormBuilder($recursos)

            ->add('Nombre', TextType::class)
            ->add('Categoria', ChoiceType::class, array(
                'choices'=>array($categorias),

                'choice_label'=>function($categorias, $key){
                },
            ))
            ->add('email', ChoiceType::class, array(
                'choices'=>array($user),

                'choice_label'=>function($user, $key){
                },
            ))
        
            ->add('Guardar', SubmitType::class, ['label' => 'Crear Recurso'])
                
            ->getForm();
         
            
            $form->handleRequest($request);


            if ($form->isSubmitted() && $form->isValid()) {
             
                $recursos = $form->getData();

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($recursos);
                $entityManager->flush();

                return $this->render('recursos/guardado.html.twig');
            };
            return $this->render('recursos/agregar.html.twig', [
                'form' => $form->createView(),
                ]);
    }
    /**
     * @Route("/recursos/editar/{id}", name="recursos_editar", methods={"GET","POST"})
     */
    public function editar(Request $request, $id)    {
        $em = $this->getDoctrine()->getManager();
        $recursos = $em->getRepository(Recursos::class)->find($id);
        $user = $this->getDoctrine()->getRepository(User::class)->findAll();
        $categorias = $this->getDoctrine()->getRepository(categorias::class)->findAll();
        $form = $this->createFormBuilder($recursos)
    
            ->add('Nombre', TextType::class)
            ->add('Categoria', ChoiceType::class, array(
                'choices'=>array($categorias),
                'choice_label'=>function($categorias){
                },
            ))
            ->add('email', ChoiceType::class, array(
                'choices'=>array($user),
                'choice_label'=>function($user, $key){
                },
            ))
            ->add('Guardar', SubmitType::class, ['label' => 'Crear Recurso'])  
            ->getForm();
            
            $form->handleRequest($request); 

            if ($form->isSubmitted() && $form->isValid()) {
             
                $recursos = $form->getData();

                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($recursos, $user, $categorias);
                $entityManager->flush();
            

                return $this->render('recursos/guardado.html.twig');
            };
            return $this->render('recursos/agregar.html.twig', [
                'form' => $form->createView(),
                ]);
    }
    /**
     * @Route("/recursos/eliminar/{id}", name="recursos_eliminar")
     */
    public function eliminar($id)    {
        
        $entityManager = $this->getDoctrine()->getManager();
        $recursos = $entityManager->getRepository(Recursos::class)->find($id);
    
        $entityManager->remove($recursos);
        $entityManager->flush();
    
        return $this->render('recursos/eliminar.html.twig');
    }

}

templates/recursos/agregar.html.twig
<!DOCTYPE html>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
<!------ Include the above in your HEAD tag ---------->
<style type="text/css">
body{
  font-family: 'lato' !important;
  background-color: white;
}

/*navbar start*/

@media(min-width:768px) {

body {
  margin-top: 50px;
}
}

#wrapper {
  padding-left: 0;    
}

#page-wrapper {
  width: 100%;        
  padding: 0;
}

/* Side Navigation */

@media(min-width:768px) {

#wrapper {
  padding-left: 225px;
  padding-top: 10px;
}

#page-wrapper {
  padding: 2px 10px;
}

.side-nav {
  position: fixed;
  top: -21px;
  left: 225px;
  width: 225px;
  margin-left: -225px;
  border: none;
  border-radius: 0;
  overflow-y: auto;
  background-color: #313131;
  bottom: 0;
  overflow-x: hidden;
  padding-bottom: 40px;
  margin-top: 20px;
}

.side-nav>li>a {
  width: 225px;
  border-bottom: 1px solid #6C7278;
  margin-top: 15px;
} 
}

.navbar-inverse .navbar-collapse, .navbar-inverse .navbar-form {
  border-color: #616060 !important;
}

.navbar-ex1-collapse{
  background-color: #fff;
}

.logostyle{
  width: 50%;
  max-width: 186px;
  margin-top: 10px;
  margin-left: 55px;
}

.navbar-inverse .navbar-nav > li > .active{
  border-left: 3px solid white;
}

.nav > li > a {
  position: relative;
  display: block;
  padding: 12px 15px;
  margin-right: 15px;
}

.nav .open > a, .nav .open > a:focus, .nav .open > a:hover {
  background-color: transparent;
  border-color: white;
}

a {
  color: white !important;
  text-decoration: none;
}

.form-control-serch {
  height: 32px;
  padding: 0px 12px;
  font-size: 14px;
  line-height: 1.42857143;
  color: #555;
  background-color: #fff;
  background-image: none;
  border: 1px solid #ccc;
  border-radius: 0px 22px 22px 0px;
  box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
  transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}

.search-btn-icon{
  background-color: #fff;
  border:1px solid #E8E8E8;
  border-right: transparent !important; 
  border-top-left-radius: 30px;
  border-bottom-left-radius: 30px;
  height: 32px;
  margin-left: 200px;
}
 
.search-box{
  border-left:transparent !important;
  border-top-right-radius: 30px;
  border-bottom-right-radius: 30px;
  border:1px solid #E8E8E8;
  height: 32px;
}

.fasett {
  display: inline-block;
  font: normal normal normal 14px/1 FontAwesome;
  font-size: 25px;
  text-rendering: auto;
  color: white;
  margin-top: 10px;
  margin-right: 30px;
  cursor: pointer;
}




/*navbar end*/







</style>
<body>
<div id="throbber" style="display:none; min-height:120px;"></div>
<div id="noty-holder"></div>

<div id="wrapper">
  
    <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <i class="fa fa-bars" aria-hidden="true" style="color: white;"></i>
            </button>
            <div class="navbar-brand">   
            </div>
        </div>

        <form action="" class="navbar-form navbar-left">
            <div class="input-group">
              <div class="input-group-btn">
                  <button class="btn  search-btn-icon">
                  </button>
               </div>
               <h5>{{ app.user.username }}</h5>
            </div>     
        </form>

        <!-- Top Menu Items -->
        <div class="items">
          <ul class="nav navbar-right top-nav">        
            <li class="editpro">
                <i class="fasett fa-cog" aria-hidden="true" class="menu-button" id="menu-button"></i> 

                <a href="{{ path('app_logout') }}" class="btn btn-success">Salir</a> 
            </li>
          </ul>
        </div>

        <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
        <div class="collapse navbar-collapse navbar-ex1-collapse" style="background-color: #616060; border:1px solid #616060;">
            <ul class="nav navbar-nav side-nav">
              <a href="/inicio"><img class="logostyle" src="https://media.licdn.com/dms/image/C4E0BAQEb7ybzBjueNg/company-logo_200_200/0?e=2159024400&v=beta&t=bs67KzPA8wsx8UpyI2Btz9z2OR9X5Kb9McTh5OTceEw" alt="LOGO"></a>
                <li>
                   <a class="active" href="/recursos" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-home" aria-hidden="true"></i>   <span style="color:white;">  Administrar Recursos </span></a>
                </li>
                <li>
                    <a class="#" href="/admusuarios" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-user-o" aria-hidden="true"></i>   <span style="color:white;">  Administrar Usuarios </span></a>
                </li>
                <li>
                    <a class="#" href="/devolucion" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-calendar" aria-hidden="true"></i>   <span style="color:white;"> Devolución Anticipada </span></a>
                </li>
                <li>
                    <a class="#" href="/defectuosos" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-envelope" aria-hidden="true"></i>  <span style="color:white;"> Recursos Defectuosos </span></a>
                </li>
                <li>
                    <a class="#" href="/opciones" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-cogs" aria-hidden="true"></i>   <span style="color:white;"> Opciones </span></a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
  </nav>
  
<thead>
    <h3>Nuevo Recurso</h3>
</thead>
<tbody>
{{ form(form) }}
    <div class="my-custom-class-for-errors">
        
    </div>

    <div class="row">
        <div class="col">
            {{ form_row(form.Nombre) }}
        </div>
        <div class="col">
            {{ form_row(form.Categoria) }}
        </div>
        <div class="col">
            {{ form_row(form.email) }}
        </div>
        <div class="col">
        </div> 
    </div>
{{ form_end(form) }}
 <div>
    <a href='/recursos'>Volver</a>
    </div>
</tbody>

templates/recursos/eliminar.html.twig
<!DOCTYPE html>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
<!------ Include the above in your HEAD tag ---------->
<style type="text/css">
body{
  font-family: 'lato' !important;
  background-color: white;
}

/*navbar start*/

@media(min-width:768px) {

body {
  margin-top: 50px;
}
}

#wrapper {
  padding-left: 0;    
}

#page-wrapper {
  width: 100%;        
  padding: 0;
}

/* Side Navigation */

@media(min-width:768px) {

#wrapper {
  padding-left: 225px;
  padding-top: 10px;
}

#page-wrapper {
  padding: 2px 10px;
}

.side-nav {
  position: fixed;
  top: -21px;
  left: 225px;
  width: 225px;
  margin-left: -225px;
  border: none;
  border-radius: 0;
  overflow-y: auto;
  background-color: #313131;
  bottom: 0;
  overflow-x: hidden;
  padding-bottom: 40px;
  margin-top: 20px;
}

.side-nav>li>a {
  width: 225px;
  border-bottom: 1px solid #6C7278;
  margin-top: 15px;
} 
}

.navbar-inverse .navbar-collapse, .navbar-inverse .navbar-form {
  border-color: #616060 !important;
}

.navbar-ex1-collapse{
  background-color: #fff;
}

.logostyle{
  width: 50%;
  max-width: 186px;
  margin-top: 10px;
  margin-left: 55px;
}

.navbar-inverse .navbar-nav > li > .active{
  border-left: 3px solid white;
}

.nav > li > a {
  position: relative;
  display: block;
  padding: 12px 15px;
  margin-right: 15px;
}

.nav .open > a, .nav .open > a:focus, .nav .open > a:hover {
  background-color: transparent;
  border-color: white;
}

a {
  color: white !important;
  text-decoration: none;
}

.form-control-serch {
  height: 32px;
  padding: 0px 12px;
  font-size: 14px;
  line-height: 1.42857143;
  color: #555;
  background-color: #fff;
  background-image: none;
  border: 1px solid #ccc;
  border-radius: 0px 22px 22px 0px;
  box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
  transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}

.search-btn-icon{
  background-color: #fff;
  border:1px solid #E8E8E8;
  border-right: transparent !important; 
  border-top-left-radius: 30px;
  border-bottom-left-radius: 30px;
  height: 32px;
  margin-left: 200px;
}
 
.search-box{
  border-left:transparent !important;
  border-top-right-radius: 30px;
  border-bottom-right-radius: 30px;
  border:1px solid #E8E8E8;
  height: 32px;
}

.fasett {
  display: inline-block;
  font: normal normal normal 14px/1 FontAwesome;
  font-size: 25px;
  text-rendering: auto;
  color: white;
  margin-top: 10px;
  margin-right: 30px;
  cursor: pointer;
}




/*navbar end*/







</style>
<body>
<div id="throbber" style="display:none; min-height:120px;"></div>
<div id="noty-holder"></div>

<div id="wrapper">
  
    <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <i class="fa fa-bars" aria-hidden="true" style="color: white;"></i>
            </button>
            <div class="navbar-brand">   
            </div>
        </div>

        <form action="" class="navbar-form navbar-left">
            <div class="input-group">
              <div class="input-group-btn">
                  <button class="btn  search-btn-icon">
                  </button>
               </div>
               <h5>{{ app.user.username }}</h5>
            </div>     
        </form>

        <!-- Top Menu Items -->
        <div class="items">
          <ul class="nav navbar-right top-nav">        
            <li class="editpro">
                <i class="fasett fa-cog" aria-hidden="true" class="menu-button" id="menu-button"></i> 

                <a href="{{ path('app_logout') }}" class="btn btn-success">Salir</a> 
            </li>
          </ul>
        </div>

        <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
        <div class="collapse navbar-collapse navbar-ex1-collapse" style="background-color: #616060; border:1px solid #616060;">
            <ul class="nav navbar-nav side-nav">
              <a href="/inicio"><img class="logostyle" src="https://media.licdn.com/dms/image/C4E0BAQEb7ybzBjueNg/company-logo_200_200/0?e=2159024400&v=beta&t=bs67KzPA8wsx8UpyI2Btz9z2OR9X5Kb9McTh5OTceEw" alt="LOGO"></a>
                <li>
                   <a class="active" href="/recursos" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-home" aria-hidden="true"></i>   <span style="color:white;">  Administrar Recursos </span></a>
                </li>
                <li>
                    <a class="#" href="/admusuarios" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-user-o" aria-hidden="true"></i>   <span style="color:white;">  Administrar Usuarios </span></a>
                </li>
                <li>
                    <a class="#" href="/devolucion" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-calendar" aria-hidden="true"></i>   <span style="color:white;"> Devolución Anticipada </span></a>
                </li>
                <li>
                    <a class="#" href="/defectuosos" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-envelope" aria-hidden="true"></i>  <span style="color:white;"> Recursos Defectuosos </span></a>
                </li>
                <li>
                    <a class="#" href="/opciones" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-cogs" aria-hidden="true"></i>   <span style="color:white;"> Opciones </span></a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
  </nav>





</div>
</body>
<h1 align="center">Recurso Eliminado con Exito</h1>
<a align="rigth" href="/recursos" >Volver</a>

templates/recursos/index.html.twig
<!DOCTYPE html>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
<!------ Include the above in your HEAD tag ---------->
<style type="text/css">
body{
  font-family: 'lato' !important;
  background-color: white;
}

/*navbar start*/

@media(min-width:768px) {

body {
  margin-top: 50px;
}
}

#wrapper {
  padding-left: 0;    
}

#page-wrapper {
  width: 100%;        
  padding: 0;
}

/* Side Navigation */

@media(min-width:768px) {

#wrapper {
  padding-left: 225px;
  padding-top: 10px;
}

#page-wrapper {
  padding: 2px 10px;
}

.side-nav {
  position: fixed;
  top: -21px;
  left: 225px;
  width: 225px;
  margin-left: -225px;
  border: none;
  border-radius: 0;
  overflow-y: auto;
  background-color: #313131;
  bottom: 0;
  overflow-x: hidden;
  padding-bottom: 40px;
  margin-top: 20px;
}

.side-nav>li>a {
  width: 225px;
  border-bottom: 1px solid #6C7278;
  margin-top: 15px;
} 
}

.navbar-inverse .navbar-collapse, .navbar-inverse .navbar-form {
  border-color: #616060 !important;
}

.navbar-ex1-collapse{
  background-color: #fff;
}

.logostyle{
  width: 50%;
  max-width: 186px;
  margin-top: 10px;
  margin-left: 55px;
}

.navbar-inverse .navbar-nav > li > .active{
  border-left: 3px solid white;
}

.nav > li > a {
  position: relative;
  display: block;
  padding: 12px 15px;
  margin-right: 15px;
}

.nav .open > a, .nav .open > a:focus, .nav .open > a:hover {
  background-color: transparent;
  border-color: white;
}

a {
  color: white !important;
  text-decoration: none;
}

.form-control-serch {
  height: 32px;
  padding: 0px 12px;
  font-size: 14px;
  line-height: 1.42857143;
  color: #555;
  background-color: #fff;
  background-image: none;
  border: 1px solid #ccc;
  border-radius: 0px 22px 22px 0px;
  box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
  transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}

.search-btn-icon{
  background-color: #fff;
  border:1px solid #E8E8E8;
  border-right: transparent !important; 
  border-top-left-radius: 30px;
  border-bottom-left-radius: 30px;
  height: 32px;
  margin-left: 200px;
}
 
.search-box{
  border-left:transparent !important;
  border-top-right-radius: 30px;
  border-bottom-right-radius: 30px;
  border:1px solid #E8E8E8;
  height: 32px;
}

.fasett {
  display: inline-block;
  font: normal normal normal 14px/1 FontAwesome;
  font-size: 25px;
  text-rendering: auto;
  color: white;
  margin-top: 10px;
  margin-right: 30px;
  cursor: pointer;
}




/*navbar end*/







</style>
<body>
<div id="throbber" style="display:none; min-height:120px;"></div>
<div id="noty-holder"></div>

<div id="wrapper">
  
    <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <i class="fa fa-bars" aria-hidden="true" style="color: white;"></i>
            </button>
            <div class="navbar-brand">   
            </div>
        </div>

        <form action="" class="navbar-form navbar-left">
            <div class="input-group">
              <div class="input-group-btn">
                  <button class="btn  search-btn-icon">
                  </button>
               </div>
               <h5>{{ app.user.username }}</h5>
            </div>     
        </form>

        <!-- Top Menu Items -->
        <div class="items">
          <ul class="nav navbar-right top-nav">        
            <li class="editpro">
                <i class="fasett fa-cog" aria-hidden="true" class="menu-button" id="menu-button"></i> 

                <a href="{{ path('app_logout') }}" class="btn btn-success">Salir</a> 
            </li>
          </ul>
        </div>

        <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
        <div class="collapse navbar-collapse navbar-ex1-collapse" style="background-color: #616060; border:1px solid #616060;">
            <ul class="nav navbar-nav side-nav">
              <a href="/inicio"><img class="logostyle" src="https://media.licdn.com/dms/image/C4E0BAQEb7ybzBjueNg/company-logo_200_200/0?e=2159024400&v=beta&t=bs67KzPA8wsx8UpyI2Btz9z2OR9X5Kb9McTh5OTceEw" alt="LOGO"></a>
                <li>
                   <a class="active" href="/recursos" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-home" aria-hidden="true"></i>   <span style="color:white;">  Administrar Recursos </span></a>
                </li>
                <li>
                    <a class="#" href="/admusuarios" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-user-o" aria-hidden="true"></i>   <span style="color:white;">  Administrar Usuarios </span></a>
                </li>
                <li>
                    <a class="#" href="/devolucion" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-calendar" aria-hidden="true"></i>   <span style="color:white;"> Devolución Anticipada </span></a>
                </li>
                <li>
                    <a class="#" href="/defectuosos" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-envelope" aria-hidden="true"></i>  <span style="color:white;"> Recursos Defectuosos </span></a>
                </li>
                <li>
                    <a class="#" href="/opciones" data-toggle="collapse" data-target="#submenu-1"><i class="fa fa-cogs" aria-hidden="true"></i>   <span style="color:white;"> Opciones </span></a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
  </nav>


<div class="container-fluid">
<div class="row text-center">
<div class="col-md-12 dashhead">
<table class="records_list table table-striped table-bordered table-hover w-100" id="mydatatable">
  <thead>
    <div class="search">
    <input type="text" id="busqueda" placeholder="Buscar ...">
    <i class="fa fa-search"></i>
    </div>
    <tr>
      <th>#</th>
      <th>Nombre</th>
      <th>Categoria</th>
      <th>¿Disponible?</th>
      <th>Usuario</th>
      <th>Fecha de devolución</th>
      <td>
      {% if is_granted('ROLE_ADMIN') %}
        <a href="\recursos\agregar" class="btn btn-success">Nuevo</a>
      {% endif %}
      </td>
    </tr>
  </thead>
  <tbody>
  {% for recurso in recursos %}
    <tr>
      <th>{{ recurso.id }}</th>
      <th>{{ recurso.nombre }}</th>
      <th>
        {{ recurso.categoria.categoria }}
      </th>
       <th>
      {% if recurso.email %} 
        No
      {% else %}
        Si
      {% endif %}
      </th>
      <th>
      {% if recurso.email %}
        {{ recurso.email.email }} 
      {% endif %}
      </th> 
      
      <th>
      {% if recurso.fechaDevolucion %}
      {{ recurso.fechaDevolucion|date('d-m-Y-H-i') }}
      {% endif %}</th>
      <td>
     <a href="/recursos/editar/{{recurso.id}}" class="glyphicon glyphicon-edit"></a>
      <a href="/recursos/eliminar/{{recurso.id}}" class="glyphicon glyphicon-trash"></a>
      </td>
                </td>
                <p id="recurso"></p>
                 <script>
                    function myFunction() {
                    var txt;
                    var r = confirm("¿Desea eliminar este recurso?");
                    if (r == true) {
                        location.href="recursos/eliminar/{id}" ;
                    } else {
                        location.href="/recursos" ;
                    }
                    document.getElementById("recurso").innerHTML = txt;
                    }
                </script>
           </tr>
    {% endfor %}
  </tbody>
  
</table>
</div>
</div>
</div>

</div>
</body>